name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      start: 'app:start'
    steps:
      - uses: actions/checkout@v2
      - run: 'npm install'
      - run: npm i -g pm2
      - run: pm2 start npm --name 'pa11y' -- run $start
      - uses: ./
        with:
          start: 'app:start'