name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm install'
      - run: npm i pm2
      env: 
        start: 'app:start'
      - run: pm2 start npm --name 'pa11y' -- run {{ env.start }}
      - uses: ./
        with:
          start: 'app:start'