name: 'payy1'
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: '🖼 Running Pa11y...'
        uses: ./
        with:
          port: '3000'
          start: 'app:start'