name: 'payy1'
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install && npm i -g pm2
      - uses: ./
        with:
          port: '3000'
          start: 'app:start'